create table public.products (
  id bigint generated by default as identity not null,
  name text not null,
  retail_price_usd numeric(12, 2) null,
  retail_price_ars numeric(12, 2) null,
  wholesale_price_usd numeric(12, 2) null,
  wholesale_price_ars numeric(12, 2) null,
  brand_id bigint null,
  category_id bigint null,
  is_available_for_sale boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  stock_min numeric null default '0'::numeric,
  stock_current numeric null default '0'::numeric,
  constraint products_pkey primary key (id),
  constraint products_brand_id_fkey foreign key (brand_id) references brands (id) on update cascade on delete set null,
  constraint products_category_id_fkey foreign key (category_id) references categories (id) on update cascade on delete set null
) TABLESPACE pg_default;

CREATE POLICY "products delete"
ON public.products
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "products insert"
ON public.products
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "products select"
ON public.products
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "products update"
ON public.products
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
) WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
