create table public.business_settings (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  usd_rate numeric null,
  address text null,
  number_phone character varying null,
  constraint business_settings_pkey primary key (id)
) TABLESPACE pg_default;