create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  last_name character varying not null,
  phone_number character varying null,
  locality character varying null,
  email character varying null,
  cover text null,
  contact_method text null,
  referred_to text null,
  constraint clients_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select clients"
ON public.clients
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Clients insert"
ON public.clients
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Clients update"
ON public.clients
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Clients delete"
ON public.clients
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);