create table public.files_client (
  id bigint generated by default as identity not null,
  uploaded_at timestamp with time zone not null default now(),
  client_id bigint null,
  path text null,
  title text null,
  description text null,
  claim_id bigint null,
  balance_transaction_id bigint null,
  constraint files_client_pkey primary key (id),
  constraint files_client_claim_id_fkey foreign KEY (claim_id) references claims (id) on update CASCADE on delete CASCADE,
  constraint files_client_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.files_client ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select files_client"
ON public.files_client
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert files_client"
ON public.files_client
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete files_client"
ON public.files_client
FOR DELETE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update files_client"
ON public.files_client
FOR UPDATE
TO authenticated
USING (true);
