------- Balances table ------

create table public.balances (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  start_date date null,
  contract_date_usd numeric null,
  client_id bigint null,
  usd_current numeric null,
  budget_id bigint null,
  notes text null,
  balance_amount_ars numeric null,
  balance_amount_usd numeric null,
  constraint balances_pkey primary key (id),
  constraint balances_budget_id_fkey foreign KEY (budget_id) references budgets (id) on update CASCADE,
  constraint balances_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.balances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select balances"
ON public.balances
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);


CREATE POLICY "Public insert balances"
ON public.balances
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete balances"
ON public.balances
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update balances"
ON public.balances
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

------- Balance transactions table ------

create table public.balance_transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  balance_id bigint null,
  date date null,
  amount numeric null,
  quote_usd numeric null,
  usd_amount numeric null,
  notes text null,
  payment_method character varying null,
  is_extra_amount boolean not null default false,  
  constraint balance_transactions_pkey primary key (id),
  constraint balance_transactions_balance_id_fkey foreign KEY (balance_id) references balances (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.balance_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select balance_transactions"
ON public.balance_transactions
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert balance_transactions"
ON public.balance_transactions
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete balance_transactions"
ON public.balance_transactions
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update balance_transactions"
ON public.balance_transactions
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);
