------ RPC Function to create a board and add the creator as a member -------

create or replace function public.create_board_with_member(
    p_name text,
    p_description text,
    p_color text default '#4F5C4D'
)
returns json
language plpgsql
as $$
declare
    v_board_id bigint;
    v_user_id uuid;
begin
    v_user_id := auth.uid();

    insert into public.kanban_boards (
        name,
        description,
        color
    )
    values (
        p_name,
        p_description,
        p_color
    )
    returning id into v_board_id;

    insert into public.kanban_board_members (
        board_id,
        user_id
    )
    values (
        v_board_id,
        v_user_id
    );

    return json_build_object(
        'id', v_board_id,
        'name', p_name,
        'description', p_description,
        'color', p_color
    );
end;
$$;

------- Kanban Boards Table -------

CREATE TABLE IF NOT EXISTS kanban_boards (
    id bigint generated by default as identity not null,
    name text NOT NULL,
    description TEXT,
    color VARCHAR(7) DEFAULT '#4F5C4D',
    due_date_tolerance_yellow INTEGER DEFAULT 2, -- Days before due date to show yellow warning
    due_date_tolerance_red INTEGER DEFAULT 0 -- Days before due date to show red warning (0 = only on due date)
);

CREATE POLICY "kanban_boards insert"
ON public.kanban_boards
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_boards update"
ON public.kanban_boards
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_boards select"
ON public.kanban_boards
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM kanban_board_members kbm
        WHERE kbm.board_id = kanban_boards.id
          AND kbm.user_id = auth.uid()
    )
    OR
    EXISTS (
        SELECT 1
        FROM users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_boards delete"
ON public.kanban_boards
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Kanban Board Members Table -------

create table public.kanban_board_members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  board_id bigint not null,
  user_id uuid null,
  constraint kanban_board_members_pkey primary key (id),
  constraint kanban_board_members_board_id_fkey foreign KEY (board_id) references kanban_boards (id) on delete CASCADE,
  constraint kanban_board_members_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_kanban_board_members_board ON kanban_board_members(board_id);

CREATE POLICY "kanban_board_members insert"
ON public.kanban_board_members
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_board_members update"
ON public.kanban_board_members
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_board_members select"
ON public.kanban_board_members
FOR SELECT
TO authenticated
USING ((user_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM users u
   WHERE ((u.uid_user = auth.uid()) AND ((u.role)::text = 'Admin'::text)))))

CREATE POLICY "kanban_board_members delete"
ON public.kanban_board_members
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------- Kanban Lists Table -------

CREATE TABLE IF NOT EXISTS kanban_lists (
    id bigint generated by default as identity not null,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    board_id BIGINT NOT NULL REFERENCES kanban_boards(id) ON DELETE CASCADE,
    name text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kanban_lists_board ON kanban_lists(board_id);

CREATE POLICY "kanban_lists insert"
ON public.kanban_lists
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_lists update"
ON public.kanban_lists
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "kanban_lists select"
ON public.kanban_lists
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.kanban_board_members kbm
        WHERE kbm.board_id = kanban_lists.board_id
          AND kbm.user_id = auth.uid()
    )
);

CREATE POLICY "kanban_lists delete"
ON public.kanban_lists
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Kanban cards Table -------

CREATE TABLE IF NOT EXISTS kanban_cards (
    id bigint generated by default as identity not null,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    list_id BIGINT NOT NULL REFERENCES kanban_lists(id) ON DELETE CASCADE,
    title text NOT NULL,
    description TEXT,
    position INTEGER DEFAULT 0,
    due_date TIMESTAMPTZ,
    priority VARCHAR(20) DEFAULT 'none' CHECK (priority IN ('none', 'low', 'medium', 'high', 'very_high')),
    completed_at TIMESTAMPTZ,
);

CREATE INDEX idx_cards_list_position ON kanban_cards(list_id, position);

CREATE POLICY "kanban_cards insert"
ON public.kanban_cards
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_cards update"
ON public.kanban_cards
FOR UPDATE
TO authenticated
USING (    
  (EXISTS ( SELECT 1
   FROM (kanban_board_members kbm
     JOIN kanban_lists kl ON ((kl.board_id = kbm.board_id)))
  WHERE ((kl.id = kanban_cards.list_id) AND (kbm.user_id = auth.uid()))))
) 
WITH CHECK (
  (EXISTS ( SELECT 1
   FROM (kanban_board_members kbm
     JOIN kanban_lists kl ON ((kl.board_id = kbm.board_id)))
  WHERE ((kl.id = kanban_cards.list_id) AND (kbm.user_id = auth.uid()))))
);

CREATE POLICY "kanban_cards select"
ON public.kanban_cards
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.kanban_board_members kbm
        JOIN public.kanban_lists kl ON kl.board_id = kbm.board_id
        WHERE kl.id = kanban_cards.list_id
          AND kbm.user_id = auth.uid()
    )
);

CREATE POLICY "kanban_cards delete"
ON public.kanban_cards
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Kanban files table -------

create table public.kanban_files (
  id bigint generated by default as identity not null,
  uploaded_at timestamp with time zone not null default now(),
  kanban_card_id bigint null,
  path text null,
  display_name text null,
  constraint kanban_files_pkey primary key (id),
  constraint kanban_files_kanban_card_id_fkey foreign KEY (kanban_card_id) references kanban_cards (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX idx_files_card ON kanban_files(kanban_card_id);


CREATE POLICY "kanban_files insert"
ON public.kanban_files
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_files delete"
ON public.kanban_files
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "kanban_files select"
ON public.kanban_files
FOR SELECT
TO authenticated
USING (
  (EXISTS ( SELECT 1
   FROM ((kanban_cards kc
     JOIN kanban_lists kl ON ((kl.id = kc.list_id)))
     JOIN kanban_board_members kbm ON ((kbm.board_id = kl.board_id)))
  WHERE ((kc.id = kanban_files.kanban_card_id) AND (kbm.user_id = auth.uid()))))
);

-- RECORDAR CREAR EL BUCKET DE STORAGE PARA LOS ARCHIVOS DE KANBAN


CREATE POLICY "Kanban files select"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'kanban'
);

CREATE POLICY "Kanban files insert"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'kanban'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Kanban files delete"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'kanban'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);


------ INDEXES -------

CREATE UNIQUE INDEX idx_kanban_board_members_unique ON kanban_board_members(board_id, user_id);

CREATE INDEX idx_kanban_lists_board ON kanban_lists(board_id);

CREATE INDEX idx_cards_list_position ON kanban_cards(list_id, position);

CREATE INDEX idx_files_card ON kanban_files(kanban_card_id);