create table public.budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  accepted boolean null,
  pdf_url text null,
  pdf_path text null,
  number text null,
  amount_ars numeric null,
  type text null,
  folder_budget_id bigint null,
  amount_usd numeric null,
  sold boolean null,
  lost boolean null,
  date_of_sale timestamp with time zone null,
  usd_quote numeric null,
  constraint budgets_pkey primary key (id),
  constraint budgets_folder_budget_id_fkey foreign KEY (folder_budget_id) references folder_budgets (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Budgets select"
ON public.budgets
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budgets insert"
ON public.budgets
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budgets update"
ON public.budgets
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budgets delete"
ON public.budgets
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Folder budgets table -------

create table public.folder_budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  work_id bigint null,
  client_id bigint null,
  constraint folder_budgets_pkey primary key (id),
  constraint folder_budgets_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE,
  constraint folder_budgets_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE
) TABLESPACE pg_default;

CREATE POLICY "Folder budgets select"
ON public.folder_budgets
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Folder budgets insert"
ON public.folder_budgets
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Folder budgets update"
ON public.folder_budgets
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Folder budgets delete"
ON public.folder_budgets
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);