create table public.categories (
  id bigint generated by default as identity not null,
  name text not null,
  constraint categories_pkey primary key (id),
  constraint categories_name_key unique (name)
) TABLESPACE pg_default;