create table public.brands (
  id bigint generated by default as identity not null,
  name text not null,
  constraint brands_pkey primary key (id),
  constraint brands_name_key unique (name)
) TABLESPACE pg_default;
