create table public.checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  work_id bigint not null,
  description text null,
  name text null,
  type_furniture text null,
  width numeric(10, 2) null,
  height numeric(10, 2) null,
  notes text null,
  depth numeric(10, 2) null,
  constraint checklists_pkey primary key (id),
  constraint checklists_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.checklists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Checklists select"
ON public.checklists
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Checklists insert"
ON public.checklists
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Checklists update"
ON public.checklists
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Checklists delete"
ON public.checklists
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Items checklists table -------

create table public.items_checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  checklist_id bigint not null,
  description text null,
  done boolean not null default false,
  sort_order numeric not null default 0,
  constraint items_checklists_pkey primary key (id),
  constraint items_checklists_checklist_id_fkey foreign KEY (checklist_id) references checklists (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE POLICY "Items checklists select"
ON public.items_checklists
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Items checklists insert"
ON public.items_checklists
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Items checklists update"
ON public.items_checklists
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Items checklists delete"
ON public.items_checklists
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Materials table -------

create table public.materials (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  constraint materials_pkey primary key (id),
  constraint materials_name_key unique (name)
) TABLESPACE pg_default;

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Materials select"
ON public.materials
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Materials insert"
ON public.materials
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Materials update"
ON public.materials
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Materials delete"
ON public.materials
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Predefined items table -------

create table public.items_predefined (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  items jsonb not null default '[]'::jsonb,
  material_id bigint not null,
  constraint items_predefined_pkey primary key (id),
  constraint items_predefined_material_id_fkey foreign KEY (material_id) references materials (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
ALTER TABLE public.items_predefined ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Items predefined select"
ON public.items_predefined
FOR SELECT
TO authenticated
USING (    
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Items predefined insert"
ON public.items_predefined
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Items predefined update"
ON public.items_predefined
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Items predefined delete"
ON public.items_predefined
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ Gallery checklists table -------

-- CREATE BUCKET checklists-gallery

create table public.gallery_checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  path text not null,
  item_id bigint not null,
  title text null,
  description text null,
  constraint images_checklists_pkey primary key (id),
  constraint images_checklists_item_id_fkey foreign KEY (item_id) references items_checklists (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.gallery_checklists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select gallery_checklists"
ON public.gallery_checklists
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert gallery_checklists"
ON public.gallery_checklists
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete gallery_checklists"
ON public.gallery_checklists
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update gallery_checklists"
ON public.gallery_checklists
FOR UPDATE
TO authenticated
USING (true);